### ISSUE TITLE
Backwards Transpiling?

### ISSUE THREAD

**Issue by avaidyam** [shift-js/shift-js#277]
I understand this project is Swift --> JS, but what about going JS --> Swift? This would also be a great benefit to both web and app developers.

**Comment by SharpMan** [comment]
utility? Most swift prog are mac or ios app so you need xcode gui

**Comment by avaidyam** [comment]
@SharpMan No, not really. Swift can be compiled without Xcode. JS --> Swift allows me to integrate other codebase (i.e everything NodeJS) to my project.

**Comment by Hendrixer** [comment]
This would be awesome

**Comment by gargantuan** [comment]
I'll explain my down-thumb reaction.

Firstly, how would you transpile a dynamically typed language to a statically typed language? If you've ever tried to port Javascript a javascript library to Swift by hand, you'll understand the scale of the problem. 

Secondly; What would the benefit be? The emergence of X to ES5 transpilers seems to be a response to Javascript's short comings. For web dev's wanting to write iOS apps with Javascript, there's plenty of options already available such as PhoneGap or React native. 

I personally see Swift usurping Javascript as the lingua franca of programming languages in the future. It's basically what everyone want's from the Javascript of tomorrow, today.

**Comment by avaidyam** [comment]
Swift is statically typed _by choice._ You're forgetting we can leverage the ObjC runtime for a highly dynamic runtime. Have **you** ever tried porting a JS library to Objective-C? There's no difference between this and using Swift syntactically. 

The benefit is simply: **I'm not a fan of using JS for certain libraries that shouldn't be written in JS.** Again, as a developer, you may see JS as the future. That's perfectly acceptable, but we don't see eye to eye. It's just an opinion, and instead of brushing off the prospect of a "backwards transpiler" with _"I don't see a use for it."_ I would prefer some cooperative and constructive criticism.

**Comment by gargantuan** [comment]
I thought I was being constructive. I have tried to convert javascript libraries to swift and it was unfeasibly difficult. Specifically this library for SpriteKit.

https://github.com/r3mi/poly2tri.js

Give it a go, let me know how you get on. 

I'll also add, it's not that "I don't see a use for it.", it's that I don't see the value of it, especially when you compare it to other features that are yet to be implemented. 

It's not my code base and I'm not contributing so this really is just, like, my opinion man*, and maybe the contributors feel differently; But to me it feels like a distraction from the principal objective - Transpiling Swift to Javascript so that the creators of iOS and OSX applications can create the web components for their app (web API, utilities, libraries etc) in the same language their native application is written in. 

There are already a few serious options for writing native apps in Javascript. 

*Big Lebowski reference

**Comment by avaidyam** [comment]
I'm not sure you realized this, but there is an existing Java variant, which you could easily run through J2ObjC (a google tool), and then use Xcode to convert it to Swift. A little syntax fixing and you would be fine.

Again, you may not see the value of XYZ, but _I do!_ I'm not detracting from implementing other features at all, in fact, I'm just placing a reminder that this would be a cool thing to have.

I only made this issue as a suggestion, because I need to go the other way around. Nothing more.
